---
- name: get apt repo key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
- name: Install apt-transport
  apt:
    name: apt-transport-https
    state: present
  # apt_key:
  #   url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  #   state: present

- name: install apt repo
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
    # repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    # state: present
    # filename: elastic-6.x.list
    # update_cache: yes

- name: install java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
- name: Copy Config file
  copy:
    src: /home/ubuntu/roles/elasticsearch/template/elasticsearch.yml 
    dest: /etc/elasticsearch/elasticsearch.yml
# - name: reload systemd config
#   systemd: daemon_reload=yes

- name: enable service elasticsearch and ensure it is not masked
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running
  systemd: state=restarted name=elasticsearch